# Generated by Django 4.1 on 2022-10-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('img', models.ImageField(default='', upload_to='')),
                ('author', models.CharField(blank=True, default='Unknown', max_length=20)),
                ('publish_date', models.DateField(auto_now=True)),
                ('sub_category', models.CharField(default='', max_length=100)),
                ('readtime', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
