# Generated by Django 4.1 on 2022-10-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogs_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='timeStamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
