# Generated by Django 4.1 on 2022-10-11 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogs_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='sub_category',
        ),
    ]
